Repository maxitg/SetReplace, pull requests merged in 2020-04, with the labels that each got.

#282 Fix style inheritance
  Kernel/WolframModelPlot.m
  Tests/WolframModelPlot.wlt
Labels: critical, weed

#271 Offline Build
  scripts/buildInit.wl
Labels: weed

#273 Allow context change in internal builds
  build.wls
  scripts/buildInit.wl
  scripts/packPaclet.wls
  scripts/re_build_SetReplace.xml
Labels: feature

#281 graphicsQ and checkGraphics
  Kernel/testUtilities.m
  Tests/RulePlot.wlt
  Tests/WolframModelEvolutionObject.wlt
  Tests/WolframModelPlot.wlt
Labels: weed

#283 RulePlot hypergraph styles
  Kernel/RulePlot.m
  Tests/RulePlot.wlt
Labels: feature

#284 Improved vertex labels
  Kernel/WolframModelPlot.m
Labels: feature

#285 Any highlight style
  Kernel/WolframModelPlot.m
  Tests/RulePlot.wlt
  Tests/WolframModelPlot.wlt
Labels: feature

#287 Fix style parsing for empty hypergraphs
  Kernel/WolframModelPlot.m
  Tests/WolframModelEvolutionObject.wlt
  Tests/WolframModelPlot.wlt
Labels: weed

#288 HypergraphUnificationsPlot
  Kernel/HypergraphUnificationsPlot.m
  Tests/HypergraphUnificationsPlot.wlt
Labels: feature

#289 connectedHypergraphQ
  Kernel/utilities.m
  Tests/utilities.wlt
Labels: feature

#292 Fix compilation on 32-bit Windows.
  libSetReplace/SetReplace.cpp
Labels: weed

#295 Fix automatic time constraint
  Kernel/WolframModel.m
  Tests/WolframModel.wlt
Labels: critical, weed

#296 Fix created edge style
  Kernel/style.m
Labels: weed

#290 WolframModelRuleValue
  Kernel/WolframModelRuleValue.m
  Tests/WolframModelRuleValue.wlt
Labels: feature

#291 Contributing guidelines
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/weed_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  READMEImages/ArgumentChecks.png
  READMEImages/NoArgumentChecks.png
Labels: feature

#303 Link to launch materials
  README.md
Labels: feature

#302 Clean up usage messages
  Kernel/HypergraphUnifications.m
  Kernel/HypergraphUnificationsPlot.m
  Kernel/ToPatternRules.m
  Kernel/WolframModelRuleValue.m
  Kernel/WolframPhysicsProjectStyleData.m
Labels: feature

#304 SetReplace 0.3
  PacletInfo.m
  scripts/buildInit.wl
  scripts/version.wl
Labels: feature

#308 Add header cstdint to IDTypes providing int64_t
  libSetReplace/IDTypes.hpp
Labels: refactor

#311 Reduced number of hash table lookups and memory allocations
  libSetReplace/Expression.cpp
  libSetReplace/Match.cpp
  libSetReplace/SetReplace.cpp
Labels: optimization, refactor

#301 Fix VertexNamingFunction for non-atom non-list edges
  Kernel/WolframModel.m
  Tests/WolframModel.wlt
Labels: weed

#313 Add syntax highlighting to markdown files
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/weed_report.md
  README.md
Labels: documentation
