Repository maxitg/SetReplace, pull requests merged in 2020-12, with the labels that each got.

#536 Fix typo in DevUtils documentation
  README.md
Labels: documentation, english, weed

#535 Introduce rasterization functions to DevUtils
  .github/CONTRIBUTING.md
  DevUtils/Rasterization.m
Labels: feature, infrastructure, wolfram language

#540 Save build artifacts in CI
  .circleci/config.yml
Labels: feature, infrastructure

#539 Linter pre-push hook
  .circleci/config.yml
  .github/CONTRIBUTING.md
  lint.sh
  scripts/git_hooks/pre-push
  scripts/install_git_hooks.sh
Labels: feature, infrastructure

#544 Add CMake build directory to gitignore
  .gitignore
Labels: infrastructure, weed

#545 Fix Xcode warnings
  SetReplace.xcodeproj/project.pbxproj
  libSetReplace/Match.cpp
  libSetReplace/Parallelism.cpp
  libSetReplace/Parallelism.hpp
Labels: c++, weed

#546 Documentation fixes
  .github/CONTRIBUTING.md
  Documentation/SymbolsAndFunctions/HypergraphPlot.md
  Documentation/SymbolsAndFunctions/UtilityFunctions/HypergraphToGraph.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/MultiwayQ.md
  README.md
Labels: documentation

#547 Add WolframLibrary.h and related headers to the repository
  .circleci/config.yml
  .github/CONTRIBUTING.md
  CMakeLists.txt
  SetReplace.xcodeproj/project.pbxproj
  cmake/FindMathematica.cmake
  cmake/SetReplaceConfig.cmake.in
  libSetReplace/SetReplace.hpp
  libSetReplace/WolframHeaders/WolframLibrary.h
  libSetReplace/WolframHeaders/dllexport.h
  libSetReplace/WolframHeaders/extern.h
Labels: c++, infrastructure, refactor

#549 Remove Fire CI config
  .fire.yml
Labels: infrastructure

#550 Format pre-commit hook
  .github/CONTRIBUTING.md
  scripts/git_hooks/pre-commit
  scripts/install_git_hooks.sh
Labels: feature, infrastructure

#543 Add parallelism files to the Xcode project
  SetReplace.xcodeproj/project.pbxproj
Labels: infrastructure, weed

#553 Prevent empty lists being treated as options
  Kernel/WolframModelEvolutionObject.m
  Tests/WolframModelEvolutionObject.wlt
Labels: analysis, feature, wolfram language

#554 Change non-standard types to int
  libSetReplace/Match.cpp
  libSetReplace/Parallelism.cpp
  libSetReplace/Parallelism.hpp
Labels: c++, evolution, refactor

#556 Fix performanceTest.wls for DevUtils
  .circleci/config.yml
  performanceTest.wls
Labels: infrastructure, weed, wolfram language

#555 CMake: Windows warnings
  .github/CONTRIBUTING.md
  CMakeLists.txt
Labels: cmake, feature, infrastructure

#558 CI job: Windows
  .circleci/config.yml
Labels: feature, infrastructure

#559 Googletest: Computable results
  .circleci/config.yml
  .gitignore
  libSetReplaceTest.sh
Labels: feature, infrastructure

#560 Linux32 CI
  .circleci/config.yml
Labels: feature, infrastructure

#563 Fix CMake Warning
  CMakeLists.txt
Labels: cmake, infrastructure, weed

#564 Standardize Shebangs
  .circleci/test.sh
  libSetReplaceTest.sh
  lint.sh
  scripts/git_hooks/pre-push
  scripts/install_git_hooks.sh
Labels: bash, feature, infrastructure

#561 CI: Build LibraryResources without Wolfram Language
  .circleci/config.yml
  scripts/buildLibraryResources.sh
Labels: bash, feature, infrastructure

#562 CI job: macOS
  .circleci/config.yml
Labels: bash, feature, infrastructure

#565 Alpine Linux 64 CI
  .circleci/config.yml
  libSetReplace/Event.cpp
  libSetReplace/Parallelism.cpp
  libSetReplace/test/Parallelism_tests.cpp
  libSetReplace/test/profile_tests.cpp
Labels: feature, infrastructure

#568 CI: Build multi-platform paclet
  .circleci/config.yml
  .github/CONTRIBUTING.md
Labels: feature, infrastructure

#570 set -eo pipefail in all bash scripts
  .circleci/test.sh
  libSetReplaceTest.sh
  lint.sh
  scripts/install_git_hooks.sh
Labels: bash, infrastructure, weed

#572 Fix line width violations
  Tests/HypergraphPlot.wlt
  Tests/SetReplaceFixedPoint.wlt
  Tests/SetReplaceFixedPointList.wlt
  Tests/SetReplaceList.wlt
  Tests/WolframModelEvolutionObject.wlt
  Tests/convexHullPolygon.wlt
  performanceTest.wls
  test.wls
Labels: refactor

#566 Bash Formatter/Linter
  .circleci/config.yml
  .circleci/test.sh
  .github/CONTRIBUTING.md
  libSetReplaceTest.sh
  lint.sh
  scripts/buildLibraryResources.sh
  scripts/git_hooks/pre-commit
  scripts/git_hooks/pre-push
  scripts/install_git_hooks.sh
Labels: bash, feature, infrastructure

#569 Remove internal Wolfram build scripts
  DevUtils/GitLink.m
  scripts/re_build_SetReplace.xml
  scripts/re_build_library.wls
  scripts/re_pack_paclet.wls
  scripts/run_re_scripts.wls
Labels: infrastructure, refactor, wolfram language

#576 CI: Fix CMake install script to use the new universal archive
  .circleci/config.yml
Labels: critical, infrastructure, weed

#577 Fix early exit from clang-format in ./lint.sh
  lint.sh
Labels: bash, infrastructure, weed

#578 Parallel WL Tests on CI
  .circleci/config.yml
  .circleci/test.sh
Labels: bash, infrastructure, optimization

#581 Markdown Linter
  .circleci/config.yml
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/weed_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .markdownlint.json
  Documentation/SymbolsAndFunctions/HypergraphPlot.md
  Documentation/SymbolsAndFunctions/RulePlotOfWolframModel.md
  Documentation/SymbolsAndFunctions/SetReplace.md
  Documentation/SymbolsAndFunctions/ToPatternRules.md
  Documentation/SymbolsAndFunctions/UtilityFunctions/BuildData.md
  Documentation/SymbolsAndFunctions/UtilityFunctions/GeneralizedGridGraph.md
  Documentation/SymbolsAndFunctions/UtilityFunctions/HypergraphAutomorphismGroup.md
  Documentation/SymbolsAndFunctions/UtilityFunctions/HypergraphToGraph.md
  Documentation/SymbolsAndFunctions/UtilityFunctions/HypergraphUnifications.md
  Documentation/SymbolsAndFunctions/UtilityFunctions/IsomorphicHypergraphQ.md
  Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md
  Documentation/SymbolsAndFunctions/UtilityFunctions/Subhypergraph.md
  Documentation/SymbolsAndFunctions/UtilityFunctions/WolframModelRuleValue.md
  Documentation/SymbolsAndFunctions/UtilityFunctions/WolframPhysicsProjectStyleData.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/EventDeduplication.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/EventOrderingFunction.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/EventSelectionFunction.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/IncludeBoundaryEvents.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/IncludePartialGenerations.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/Method.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/TimeConstraint.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/VertexNamingFunction.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/AllEdgesThroughoutEvolution.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/CausalGraphs.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/CreatorAndDestroyerEvents.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/EdgeAndEventGenerations.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/ElementCountLists.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/EventCounts.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/Events.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/EventsAndStates.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/ExpressionSeparations.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FinalElementCounts.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/GenerationCounts.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/MultiwayQ.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/PlotsOfEvents.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/PlotsOfStates.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/RuleIndicesForEvents.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/Rules.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/States.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/StatesAsEdgeIndices.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/TerminationReason.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/TotalElementCounts.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/Version.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md
  README.md
  Research/ConfluenceAndCausalInvariance/ConfluenceAndCausalInvariance.md
  Research/LocalMultiwaySystem/LocalMultiwaySystem.md
  lint.sh
Labels: feature, infrastructure
