Repository maxitg/SetReplace, pull requests merged in 2020-11, with the labels that each got.

#501 Confluence and Causal Invariance: Link original glossary
  Research/ConfluenceAndCausalInvariance/ConfluenceAndCausalInvariance.md
Labels: convenience, english

#502 Confluence and Causal Invariance: Remove MultiwaySystem quotes
  Research/ConfluenceAndCausalInvariance/ConfluenceAndCausalInvariance.md
Labels: english, weed

#503 MultiwayQ property
  Documentation/Images/MultiwayExpressionsEventsGraphEchoed.png
  Documentation/Images/SinglewayExpressionsEventsGraphEchoed.png
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/MultiwayQ.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md
  Kernel/WolframModelEvolutionObject.m
  README.md
  Tests/WolframModelEvolutionObject.wlt
Labels: analysis, feature, wolfram language

#512 Remove asterisk from SetReplace*.md
  Documentation/SymbolsAndFunctions/SetReplace.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md
  README.md
Labels: critical, weed

#513 Add IsomorphicHypergraphQ to the main README file
  README.md
Labels: weed

#514 Cache libSetReplace build
  .gitignore
  build.wls
  scripts/buildInit.wl
Labels: infrastructure, optimization, wolfram language

#517 Confluence and Causal Invariance: DQA edits
  Research/ConfluenceAndCausalInvariance/ConfluenceAndCausalInvariance.md
Labels: analysis, english, refactor

#519 Use a temporary build directory
  build.wls
  scripts/buildInit.wl
Labels: infrastructure

#518 Improve libSetReplace loading
  Kernel/setSubstitutionSystem$cpp.m
Labels: infrastructure, weed, wolfram language

#511 RandomHypergraph
  Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md
  Kernel/RandomHypergraph.m
  README.md
  Tests/RandomHypergraph.wlt
Labels: feature

#504 Features Extractor (on Causal Graphs)
  Documentation/Images/FeatureVectorFeatureSpacePlot.png
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md
  Kernel/WolframModelEvolutionObject.m
  README.md
  Tests/WolframModelEvolutionObject.wlt
Labels: analysis, feature, wolfram language

#527 Confluence and Causal Invariance: Mention classical sequential growth models
  Research/ConfluenceAndCausalInvariance/ConfluenceAndCausalInvariance.md
Labels: english

#520 Load GeneralUtilities in Kernel/init.m, and add back some simple macro sugar
  Kernel/globals.m
  Kernel/init.m
  Tests/buildData.wlt
Labels: feature, infrastructure, wolfram language

#526 New flags and QoL improvements in test script
  .circleci/test.sh
  .github/CONTRIBUTING.md
  .gitignore
  test.wls
Labels: feature, infrastructure, wolfram language

#537 Use HypergraphPlot as a default name for WolframModelPlot
  .github/CONTRIBUTING.md
  Documentation/Images/HypergraphPlot.png
  Documentation/SymbolsAndFunctions/HypergraphPlot.md
  Documentation/SymbolsAndFunctions/RulePlotOfWolframModel.md
  Documentation/SymbolsAndFunctions/UtilityFunctions/HypergraphAutomorphismGroup.md
  Documentation/SymbolsAndFunctions/UtilityFunctions/WolframPhysicsProjectStyleData.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/EdgeAndEventGenerations.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/PlotsOfStates.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/States.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/StatesAsEdgeIndices.md
  Kernel/HypergraphPlot.m
  Kernel/HypergraphUnificationsPlot.m
  Kernel/RulePlot.m
  Kernel/WolframModelEvolutionObject.m
  Kernel/style.m
  README.md
  Research/LocalMultiwaySystem/LocalMultiwaySystem.md
  Tests/HypergraphPlot.wlt
  Tests/HypergraphUnificationsPlot.wlt
  Tests/RulePlot.wlt
  Tests/WolframModelEvolutionObject.wlt
  Tests/performance.wlt
Labels: refactor, wolfram language

#538 Fix compilation on 32-bit
  libSetReplace/SetReplace.cpp
Labels: c++, weed
