Repository maxitg/SetReplace, pull requests merged in 2020-03, with the labels that each got.

#196 Physics Project paclet info
  SetReplace/PacletInfo.m
Labels: enhancement

#201 Listable WolframModelPlot
  SetReplace/WolframModelPlot.m
  SetReplace/WolframModelPlot.wlt
Labels: enhancement

#205 multisetUnion
  SetReplace/utilities.m
  SetReplace/utilities.wlt
Labels: enhancement

#208 WolframModel properties autocompletion
  SetReplace/WolframModel.m
  SetReplace/WolframModelEvolutionObject.m
Labels: enhancement

#209 Custom context
  build.wls
  scripts/buildInit.wl
Labels: enhancement

#211 WolframPhysicsProjectStyleData
  SetReplace/WolframPhysicsProjectStyleData.m
  SetReplace/WolframPhysicsProjectStyleData.wlt
  SetReplace/style.m
Labels: enhancement

#255 Fix ToPatternRules pattern naming
  SetReplace/ToPatternRules.m
  SetReplace/ToPatternRules.wlt
Labels: bug

#256 Frame style test fix
  SetReplace/RulePlot.wlt
Labels: weed

#206 multisetFilterRules
  SetReplace/utilities.m
  SetReplace/utilities.wlt
Labels: feature

#257 Small arrow in RulePlot
  SetReplace/style.m
Labels: feature

#260 Fix event generations
  SetReplace/WolframModelEvolutionObject.m
  SetReplace/WolframModelEvolutionObject.wlt
Labels: weed

#262 Fix the test with inconsistent style group and element
  SetReplace/WolframPhysicsProjectStyleData.wlt
Labels: weed

#261 Branchial graph EdgeStyle
  SetReplace/style.m
Labels: feature

#266 Multiway styles
  Kernel/style.m
Labels: feature

#269 Generic, 3D, and rulial graph styles
  Kernel/style.m
Labels: feature

#268 Adaptive arrowheads
  Kernel/WolframModelPlot.m
  Kernel/style.m
  Tests/WolframModelPlot.wlt
Labels: feature

#264 Fix empty hypergraph unifications
  Kernel/HypergraphUnifications.m
  Tests/HypergraphUnifications.wlt
Labels: weed

#270 Git SHA and Build Time
  Kernel/buildData.m
  Tests/buildData.wlt
  build.wls
  scripts/buildInit.wl
  scripts/packPaclet.wls
Labels: feature

#274 WolframModelPlot drawing optimizations
  Kernel/WolframModelPlot.m
  Kernel/arrow.m
  Kernel/style.m
  Tests/WolframModelPlot.wlt
Labels: optimization

#275 Secure C++ code
  libSetReplace/IDTypes.hpp
  libSetReplace/Match.cpp
  libSetReplace/Match.hpp
  libSetReplace/Set.cpp
  libSetReplace/Set.hpp
  libSetReplace/SetReplace.cpp
Labels: feature

#272 Automatic Steps
  Kernel/WolframModel.m
  Kernel/WolframModelEvolutionObject.m
  Tests/WolframModel.wlt
Labels: feature

#278 Change generical line plot styles
  Kernel/style.m
Labels: feature
