Repository maxitg/SetReplace, pull requests merged in 2020-06, with the labels that each got.

#364 C++ multithread rules
  CPPLINT.cfg
  Tests/correctness.wlt
  libSetReplace/Expression.cpp
  libSetReplace/Match.cpp
  libSetReplace/Match.hpp
  libSetReplace/Set.cpp
  libSetReplace/test/Set_test.cpp
  lint.sh
Labels: c++, evolution, optimization

#370 Fix macOS compilation for std::shared_mutex
  README.md
  scripts/buildInit.wl
Labels: c++, critical, infrastructure, weed

#373 Fix test header formatting
  .clang-format
  libSetReplace/test/Set_test.cpp
Labels: infrastructure, weed

#374 Fix Xcode project
  SetReplace.xcodeproj/project.pbxproj
Labels: infrastructure, weed

#368 EventSelectionFunction in libSetReplace
  CMakeLists.txt
  Kernel/setSubstitutionSystem$cpp.m
  SetReplace.xcodeproj/project.pbxproj
  libSetReplace/Event.cpp
  libSetReplace/Event.hpp
  libSetReplace/Expression.hpp
  libSetReplace/IDTypes.hpp
  libSetReplace/Match.cpp
  libSetReplace/Match.hpp
  libSetReplace/Set.cpp
  libSetReplace/Set.hpp
  libSetReplace/SetReplace.cpp
  libSetReplace/SetReplace.hpp
  libSetReplace/test/Set_test.cpp
Labels: c++, evolution, refactor

#380 Event-based evolution object
  Kernel/WolframModel.m
  Kernel/WolframModelEvolutionObject.m
  Kernel/makeMessage.m
  Kernel/setSubstitutionSystem$cpp.m
  Kernel/setSubstitutionSystem$wl.m
  README.md
  Tests/WolframModelEvolutionObject.wlt
Labels: analysis, evolution, refactor, weed, wolfram language

#382 ExpressionsEventsGraph
  Kernel/WolframModelEvolutionObject.m
  Kernel/style.m
  README.md
  READMEImages/ArithmeticModelCausalGraph.png
  READMEImages/ArithmeticModelExpressionsEventsGraph.png
  READMEImages/ArithmeticModelLayeredCausalGraph.png
  READMEImages/CausalGraphWithFinalEvent.png
  READMEImages/ExpressionsEventsGraphWithBoundaryEvents.png
  READMEImages/FoliatedCausalGraph.png
  READMEImages/FoliatedExpressionsEventsGraph.png
  Tests/WolframModelEvolutionObject.wlt
Labels: analysis, feature, wolfram language

#379 Split correctness tests
  Tests/correctness.wlt
  Tests/eventOrderingFunction.wlt
  Tests/evolutionConsistency.wlt
  Tests/lowLevelEvolution.wlt
  Tests/matching.wlt
  Tests/symbolicEvolution.wlt
Labels: evolution, refactor, test, wolfram language

#381 EventSelectionFunction
  Kernel/RulePlot.m
  Kernel/SetReplace.m
  Kernel/SetReplaceAll.m
  Kernel/SetReplaceFixedPoint.m
  Kernel/SetReplaceFixedPointList.m
  Kernel/SetReplaceList.m
  Kernel/WolframModel.m
  Kernel/makeMessage.m
  Kernel/setSubstitutionSystem$cpp.m
  Kernel/setSubstitutionSystem.m
  README.md
  READMEImages/BranchlikeMatching.png
  READMEImages/GlobalSpacelikeEvolution.png
  READMEImages/MultiwayExpressionsEventsGraph.png
  READMEImages/SpacelikeMatching.png
  READMEImages/TimelikeMatching.png
  Tests/SetReplace.wlt
  Tests/SetReplaceAll.wlt
  Tests/SetReplaceFixedPoint.wlt
  Tests/SetReplaceFixedPointList.wlt
  Tests/SetReplaceList.wlt
  Tests/WolframModel.wlt
  Tests/WolframModelEvolutionObject.wlt
  Tests/eventSelectionFunction.wlt
  Tests/evolutionConsistency.wlt
Labels: evolution, feature, wolfram language
