Repository maxitg/SetReplace, pull requests merged in 2020-10, with the labels that each got.

#422 Fix WL code formatting
  Kernel/$graphIcon.m
  Kernel/SetReplace.m
  Kernel/SetReplaceAll.m
  Kernel/SetReplaceFixedPoint.m
  Kernel/SetReplaceFixedPointList.m
  Kernel/SetReplaceList.m
  Kernel/ToPatternRules.m
  Kernel/WolframModel.m
  Kernel/WolframModelEvolutionObject.m
  Kernel/makeMessage.m
  Kernel/setSubstitutionSystem$cpp.m
  Kernel/setSubstitutionSystem.m
  Kernel/usageString.m
Labels: refactor, wolfram language

#424 Fix data structure spelling
  Research/LocalMultiwaySystem/LocalMultiwaySystem.md
Labels: writing

#425 Documentation links from Local Multiway System note
  Research/LocalMultiwaySystem/LocalMultiwaySystem.md
Labels: writing

#435 Make .clang-format consistent with cpplint
  .clang-format
  libSetReplace/test/Set_test.cpp
Labels: infrastructure, weed

#432 convexHullPolygon
  Kernel/convexHullPolygon.m
  Tests/convexHullPolygon.wlt
Labels: critical, feature, utilities

#433 Fix WolframModelPlot for Wolfram Language 12.2
  Kernel/WolframModelPlot.m
Labels: critical, visualization, weed

#439 Build with AbsoluteFileName
  install.wls
  scripts/buildInit.wl
  test.wls
Labels: weed

#437 C++ Profiling Tests
  libSetReplace/test/CMakeLists.txt
  libSetReplace/test/profile_tests.cpp
Labels: c++, evolution, test

#431 Adding Subhypergraph & WeakSubhypergraph utilities
  Kernel/Subhypergraph.m
  README.md
  Tests/Subhypergraph.wlt
Labels: feature, utilities, wolfram language

#441 Use italics consistently for SetReplace
  README.md
Labels: english, weed

#438 Matching Optimizations
  libSetReplace/Match.cpp
Labels: c++, evolution, optimization

#444 Fix C++ tests
  libSetReplace/test/Set_test.cpp
Labels: c++, evolution, weed

#442 Correct replacement of rule symbols inside ToPatternRules
  Kernel/ToPatternRules.m
  Tests/ToPatternRules.wlt
Labels: evolution, weed, wolfram language

#450 EventOrderingFunction "Any"
  Kernel/setSubstitutionSystem$cpp.m
  Kernel/setSubstitutionSystem.m
  README.md
  READMEImages/AllEventOrderingFunctionPlots.png
  Tests/eventOrderingFunction.wlt
  libSetReplace/Match.cpp
  libSetReplace/Match.hpp
Labels: evolution, feature

#451 Removing "performance" tests from CI
  .circleci/test.sh
  test.wls
Labels: infrastructure, weed

#452 Add VertexLabels -> "Index" for "ExpressionsEventsGraph"
  Kernel/WolframModelEvolutionObject.m
  README.md
  READMEImages/MultiwayExpressionsEventsGraphIndex.png
Labels: convenience, feature

#440 Update contributing guidelines
  .github/CONTRIBUTING.md
  README.md
Labels: documentation, english, infrastructure

#454 Adding "OptionNames" in SyntaxInformation of WolframModelPlot
  Kernel/WolframModelPlot.m
Labels: weed

#453 Improve performance of encodeNestedLists
  Kernel/setSubstitutionSystem$cpp.m
Labels: weed

#455 Comment about dirty repo case in $SetReplaceGitSHA tests
  Tests/buildData.wlt
Labels: documentation, infrastructure

#465 Fix broken message for invalid options in WolframModel
  Kernel/WolframModel.m
Labels: weed

#446 C++ tests in CI
  .circleci/config.yml
  libSetReplaceTest.sh
Labels: feature, infrastructure

#470 Fix Evolution object with multiple numeric arguments leaking internal symbols
  Kernel/WolframModelEvolutionObject.m
  Tests/WolframModelEvolutionObject.wlt
Labels: analysis, weed, wolfram language

#471 Added support for passing WolframModelEvolutionObject to RulePlot
  Kernel/RulePlot.m
  Kernel/WolframModelEvolutionObject.m
  Tests/RulePlot.wlt
Labels: convenience, visualization, wolfram language

#469 Avoid unnecessary step limit checks
  libSetReplace/Set.cpp
Labels: c++, evolution, optimization

#468 Parallelism manager
  CMakeLists.txt
  libSetReplace/Match.cpp
  libSetReplace/Parallelism.cpp
  libSetReplace/Parallelism.hpp
  libSetReplace/test/CMakeLists.txt
  libSetReplace/test/Parallelism_tests.cpp
Labels: c++, evolution, feature

#474 Style and grammar fixes to Local Multiway System
  Research/LocalMultiwaySystem/LocalMultiwaySystem.md
Labels: english, evolution, refactor

#473 Add IndexHypergraph function
  Kernel/HypergraphUnifications.m
  Kernel/IndexHypergraph.m
  Kernel/Subhypergraph.m
  Kernel/utilities.m
  README.md
  Tests/IndexHypergraph.wlt
  Tests/Subhypergraph.wlt
Labels: feature, utilities, wolfram language

#482 More edits to Local Multiway System
  Research/LocalMultiwaySystem/LocalMultiwaySystem.md
Labels: english, refactor

#461 Replace all Module's with ModuleScope
  .github/CONTRIBUTING.md
  Kernel/GeneralizedGridGraph.m
  Kernel/HypergraphAutomorphismGroup.m
  Kernel/HypergraphUnifications.m
  Kernel/HypergraphUnificationsPlot.m
  Kernel/RulePlot.m
  Kernel/SetReplace.m
  Kernel/SetReplaceAll.m
  Kernel/SetReplaceFixedPoint.m
  Kernel/SetReplaceFixedPointList.m
  Kernel/SetReplaceList.m
  Kernel/ToPatternRules.m
  Kernel/WolframModel.m
  Kernel/WolframModelEvolutionObject.m
  Kernel/WolframModelPlot.m
  Kernel/WolframModelRuleValue.m
  Kernel/argumentsChecking.m
  Kernel/arrow.m
  Kernel/convexHullPolygon.m
  Kernel/setSubstitutionSystem$cpp.m
  Kernel/setSubstitutionSystem$wl.m
  Kernel/setSubstitutionSystem.m
  Kernel/testUtilities.m
  Tests/matching.wlt
  performanceTest.wls
  scripts/buildInit.wl
  test.wls
Labels: refactor, wolfram language

#491 Local Multiway System: add missing curly brace
  Research/LocalMultiwaySystem/LocalMultiwaySystem.md
Labels: english, weed

#479 Confluence and Causal Invariance
  Research/ConfluenceAndCausalInvariance/ConfluenceAndCausalInvariance.md
  Research/ConfluenceAndCausalInvariance/Images/CausalInvariantCausalGraphs.png
  Research/ConfluenceAndCausalInvariance/Images/CausalInvariantEvolutions.png
  Research/ConfluenceAndCausalInvariance/Images/CausalInvariantMultiwaySystem.png
  Research/ConfluenceAndCausalInvariance/Images/CausalInvariantStatesGraph.png
  Research/ConfluenceAndCausalInvariance/Images/ConfluentCausalGraphs.png
  Research/ConfluenceAndCausalInvariance/Images/ConfluentStatesGraph.png
  Research/ConfluenceAndCausalInvariance/Images/LargeCausalInvariantEvolution.png
  Research/ConfluenceAndCausalInvariance/Images/LargeConfluentEvolution.png
Labels: analysis, english, research

#496 Fix links to new documentation in Confluence and Causal Invariance note
  Research/ConfluenceAndCausalInvariance/ConfluenceAndCausalInvariance.md
Labels: english, weed

#490 Add HypergraphToGraph function
  Documentation/Images/HypergraphToGraphDirectedDistancePreserving.png
  Documentation/Images/HypergraphToGraphStructurePreserving.png
  Documentation/Images/HypergraphToGraphUndirectedDistancePreserving.png
  Documentation/SymbolsAndFunctions/UtilityFunctions/HypergraphToGraph.md
  Kernel/HypergraphToGraph.m
  Kernel/style.m
  README.md
  Tests/HypergraphToGraph.wlt
Labels: analysis, feature

#492 IsomorphicHypergraphQ
  Documentation/SymbolsAndFunctions/UtilityFunctions/IsomorphicHypergraphQ.md
  Kernel/IsomorphicHypergraphQ.m
  Tests/IsomorphicHypergraphQ.wlt
Labels: analysis, feature

#499 Documentation for RulePlot support of WolframModelEvolutionObject
  Documentation/Images/RulePlotWolframModelEvolutionObjectInput.png
  Documentation/SymbolsAndFunctions/RulePlotOfWolframModel.md
Labels: documentation
