Repository maxitg/SetReplace, pull requests merged in 2020-05, with the labels that each got.

#326 Readme and Contributing grammar/spelling corrections
  .github/CONTRIBUTING.md
  README.md
Labels: documentation

#318 C++ Style contributing guidelines update
  .github/CONTRIBUTING.md
Labels: documentation

#331 Verify test completion in CI
  .circleci/config.yml
  .circleci/test.sh
  test.wls
Labels: critical, weed

#328 Cpp optimizations
  libSetReplace/Expression.cpp
  libSetReplace/Expression.hpp
  libSetReplace/Match.cpp
  libSetReplace/Match.hpp
  libSetReplace/Set.cpp
  libSetReplace/Set.hpp
  libSetReplace/SetReplace.cpp
Labels: optimization

#337 Cpp compiler warnings
  libSetReplace/Match.cpp
  libSetReplace/Match.hpp
  libSetReplace/Set.cpp
  libSetReplace/SetReplace.cpp
  scripts/buildInit.wl
Labels: feature

#338 Performance testing tool
  .github/CONTRIBUTING.md
  performanceTest.wls
Labels: feature, testing

#293 Graphics background in style.m
  Kernel/RulePlot.m
  Kernel/WolframModelEvolutionObject.m
  Kernel/WolframModelPlot.m
  Kernel/style.m
  Tests/RulePlot.wlt
  Tests/WolframModelEvolutionObject.wlt
  Tests/WolframModelPlot.wlt
Labels: refactor, visualization, wolfram language

#356 performanceTest.wls checkout original SHA
  performanceTest.wls
Labels: infrastructure, weed, wolfram language

#340 Add CMake support
  .github/CONTRIBUTING.md
  CMakeLists.txt
  cmake/FindMathematica.cmake
  cmake/SetReplaceConfig.cmake.in
  libSetReplace/test/CMakeLists.txt
  libSetReplace/test/SetTest.cpp
Labels: feature, infrastructure

#360 Fix Windows compilation errors.
  libSetReplace/SetReplace.cpp
  scripts/buildInit.wl
Labels: c++, critical, infrastructure, weed

#361 Lint script
  .circleci/config.yml
  .clang-format
  .github/CONTRIBUTING.md
  SetReplace.xcodeproj/project.pbxproj
  libSetReplace/Expression.cpp
  libSetReplace/Expression.hpp
  libSetReplace/IDTypes.hpp
  libSetReplace/Match.cpp
  libSetReplace/Match.hpp
  libSetReplace/Rule.hpp
  libSetReplace/Set.cpp
  libSetReplace/Set.hpp
  libSetReplace/SetReplace.cpp
  libSetReplace/SetReplace.hpp
  libSetReplace/test/Set_test.cpp
  lint.sh
Labels: c++, feature, infrastructure, refactor

#363 Fully store test report in a notebook
  test.wls
Labels: infrastructure, weed

#366 CMake: Fix name of test file
  libSetReplace/test/CMakeLists.txt
Labels: c++, critical, infrastructure, weed
