Repository maxitg/SetReplace, pull requests merged in 2021-04, with the labels that each got.

#633 Fix Multiset to WolframModelEvolutionObject for "Complete" termination reason
  Kernel/MultisetToWolframModelEvolutionObject.m
  Tests/MultisetToWolframModelEvolutionObject.wlt
Labels: weed

#635 New names for MultisetSubstitutionSystem ordering functions
  Kernel/A1$GenerateMultihistory.m
  Kernel/MultisetSubstitutionSystem.m
  Tests/MultisetSubstitutionSystem.wlt
  Tests/hypergraphMatching.wlt
Labels: breaking, evolution, refactor, wolfram language

#638 MultisetSubstitutionSystem: allow patterns like {a__, b__} to be matched multiple times
  Kernel/A1$GenerateMultihistory.m
  Kernel/MultisetSubstitutionSystem.m
  Tests/MultisetSubstitutionSystem.wlt
  Tests/hypergraphMatching.wlt
  performanceTest.wls
Labels: breaking, evolution, weed, wolfram language

#630 Add ObjectProperties group to FeatureAssociation (and FeatureVector)
  Documentation/Images/FeatureAssociationExampleMultihistory.png
  Documentation/Images/FeatureAssociationExampleSingleHistory.png
  Documentation/Images/FeatureAssociationFeatureSpacePlot.png
  Documentation/Images/FeatureVectorExampleSingleHistory.png
  Documentation/Images/FeatureVectorFeatureSpacePlot.png
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md
  Kernel/WolframModelEvolutionObject.m
  Tests/WolframModelEvolutionObject.wlt
Labels: analysis, feature, wolfram language

#634 Custom files and formatting only in lint.sh
  lint.sh
  scripts/git_hooks/pre-commit
Labels: bash, feature, infrastructure
