Repository maxitg/SetReplace, pull requests merged in 2021-05, with the labels that each got.

#636 Documentation for GenerateMultihistory and MultisetSubstitutionSystem
  Documentation/Generators/$SetReplaceSystems.md
  Documentation/Generators/EventOrderingFunctions.md
  Documentation/Generators/EventSelectionParameters.md
  Documentation/Generators/GenerateMultihistory.md
  Documentation/Generators/README.md
  Documentation/Generators/StoppingConditionParameters.md
  Documentation/Images/$SetReplaceTypeGraph.png
  Documentation/Images/DifferentOrdersDifferentFinalStates.png
  Documentation/Images/DifferentOrdersDifferentHistories.png
  Documentation/Images/GenerateMultihistoryExample.png
  Documentation/Images/MaxDestroyerEvents1.png
  Documentation/Images/MaxDestroyerEvents5.png
  Documentation/Images/MaxDestroyerEventsInfinity.png
  Documentation/Images/MaxEventsExample.png
  Documentation/Images/MaxGeneration.png
  Documentation/Images/MinEventInputs0.png
  Documentation/Images/MinEventInputs2.png
  Documentation/Images/MultihistoryToWolframModelEvolutionObject.png
  Documentation/Images/MultisetMultihistory.png
  Documentation/Images/MultisetSubstitutionSystemConditionsAndSequences.png
  Documentation/Images/MultisetSubstitutionSystemExample.png
  Documentation/Images/MultisetSubstitutionSystemPartialMultihistory.png
  Documentation/Images/SameStateMultipleMatches.png
  Documentation/Images/SetReplaceObjectQOfMultihistory.png
  Documentation/Images/SetReplaceObjectTypeOfMultihistory.png
  Documentation/Images/TokenEventGraphGenerations.png
  Documentation/Properties/README.md
  Documentation/Systems/MultisetSubstitutionSystem.md
  Documentation/Systems/README.md
  Documentation/TypeSystem/$SetReplaceProperties.md
  Documentation/TypeSystem/$SetReplaceTypeGraph.md
  Documentation/TypeSystem/$SetReplaceTypes.md
  Documentation/TypeSystem/Multihistory.md
  Documentation/TypeSystem/README.md
  Documentation/TypeSystem/SetReplaceMethodImplementation.md
  Documentation/TypeSystem/SetReplaceObjectQ.md
  Documentation/TypeSystem/SetReplaceObjectType.md
  Documentation/TypeSystem/SetReplaceProperty.md
  Documentation/TypeSystem/SetReplaceType.md
  Documentation/TypeSystem/SetReplaceTypeConvert.md
  Documentation/Types/Multihistory/MultisetSubstitutionSystem0.md
  Documentation/Types/Multihistory/README.md
  Documentation/Types/README.md
  Kernel/Multihistory.m
  Research/LocalMultiwaySystem/LocalMultiwaySystem.md
Labels: documentation, english, evolution

#640 Change names in C++ to be Yellowstone consistent
  .github/CONTRIBUTING.md
  CMakeLists.txt
  Kernel/setSubstitutionSystem$cpp.m
  SetReplace.xcodeproj/project.pbxproj
  libSetReplace/AtomsIndex.cpp
  libSetReplace/AtomsIndex.hpp
  libSetReplace/Event.cpp
  libSetReplace/Event.hpp
  libSetReplace/Expression.cpp
  libSetReplace/Expression.hpp
  libSetReplace/HypergraphMatcher.cpp
  libSetReplace/HypergraphMatcher.hpp
  libSetReplace/HypergraphSubstitutionSystem.cpp
  libSetReplace/HypergraphSubstitutionSystem.hpp
  libSetReplace/IDTypes.hpp
  libSetReplace/Rule.hpp
  libSetReplace/SetReplace.cpp
  libSetReplace/SetReplace.hpp
  libSetReplace/TokenEventGraph.cpp
  libSetReplace/TokenEventGraph.hpp
  libSetReplace/WolframLanguageAPI.cpp
  libSetReplace/WolframLanguageAPI.hpp
  libSetReplace/test/CMakeLists.txt
  libSetReplace/test/HypergraphSubstitutionSystem_test.cpp
  libSetReplace/test/Set_test.cpp
  libSetReplace/test/profile_tests.cpp
Labels: c++, refactor

#644 Microsoft Visual C++ Redistributable
  Kernel/A01$libSetReplace.m
  README.md
Labels: convenience

#648 Avoid passing 64-bit ints through LibraryLink
  Kernel/setSubstitutionSystem$cpp.m
  libSetReplace/WolframLanguageAPI.cpp
Labels: weed

#647 Move TimeConstrained from setSubstitutionSystem$cpp to libSetReplace
  Kernel/setSubstitutionSystem$cpp.m
  libSetReplace/HypergraphSubstitutionSystem.cpp
  libSetReplace/HypergraphSubstitutionSystem.hpp
  libSetReplace/WolframLanguageAPI.cpp
Labels: refactor

#651 Apple ARM support
  .circleci/config.yml
  PacletInfo.m
  scripts/buildLibraryResources.sh
Labels: feature
