Repository maxitg/SetReplace, pull requests merged in 2021-02, with the labels that each got.

#528 Feature association
  Documentation/Images/FeatureAssociationFeatureSpacePlot.png
  Documentation/Images/FeatureVectorFeatureSpacePlot.png
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md
  Kernel/WolframModelEvolutionObject.m
  README.md
  Tests/WolframModelEvolutionObject.wlt
Labels: analysis, feature, wolfram language

#607 Remove unreliable references
  .github/CONTRIBUTING.md
  README.md
  Research/LocalMultiwaySystem/LocalMultiwaySystem.md
Labels: critical, weed

#606 Messages with Association arguments
  Kernel/messages.m
  Tests/message.wlt
Labels: feature, utilities, wolfram language

#603 Add pattern names in SyntaxInformation and missing usage, syntax information and syntax autocompletion
  .github/CONTRIBUTING.md
  DevUtils/BuildLibSetReplace.m
  DevUtils/Console.m
  DevUtils/FileTreeHashes.m
  DevUtils/GitLink.m
  DevUtils/PackSetReplace.m
  DevUtils/Rasterization.m
  DevUtils/init.m
  Documentation/Images/HighlightMissingArgumentsWithTemplate.png
  Kernel/AcyclicGraphTake.m
  Kernel/GeneralizedGridGraph.m
  Kernel/HypergraphAutomorphismGroup.m
  Kernel/HypergraphPlot.m
  Kernel/HypergraphToGraph.m
  Kernel/HypergraphUnifications.m
  Kernel/HypergraphUnificationsPlot.m
  Kernel/IndexHypergraph.m
  Kernel/IsomorphicHypergraphQ.m
  Kernel/RandomHypergraph.m
  Kernel/SetReplace.m
  Kernel/SetReplaceAll.m
  Kernel/SetReplaceFixedPoint.m
  Kernel/SetReplaceFixedPointList.m
  Kernel/SetReplaceList.m
  Kernel/Subhypergraph.m
  Kernel/ToPatternRules.m
  Kernel/WolframModel.m
  Kernel/WolframModelEvolutionObject.m
  Kernel/WolframModelRuleValue.m
  Kernel/WolframPhysicsProjectStyleData.m
  Kernel/buildData.m
  Kernel/setSubstitutionSystem.m
Labels: convenience, wolfram language

#612 Load-order-fixing file names
  Kernel/A0$messages.m
  Kernel/A1$utilities.m
  Kernel/A2$style.m
  Kernel/init.m
Labels: refactor, wolfram language

#608 WolframPhysicsProjectStyleData -> SetReplaceStyleData
  Documentation/SymbolsAndFunctions/UtilityFunctions/SetReplaceStyleData.md
  Kernel/A2$style.m
  Kernel/SetReplaceStyleData.m
  Kernel/WolframPhysicsProjectStyleData.m
  README.md
  Research/ConfluenceAndCausalInvariance/ConfluenceAndCausalInvariance.md
  Research/LocalMultiwaySystem/LocalMultiwaySystem.md
  Tests/HypergraphPlot.wlt
  Tests/SetReplaceStyleData.wlt
  Tests/WolframModelRuleValue.wlt
  Tests/WolframPhysicsProjectStyleData.wlt
Labels: refactor, utilities, wolfram language

#614 Fix CMake download on CI to version 3.18.6
  .circleci/config.yml
Labels: bash, critical, infrastructure, weed

#610 Causal Density Dimension
  Documentation/Images/CausalDensityDimensionInput.png
  Documentation/Images/MyrheimMeyer.png
  Documentation/SymbolsAndFunctions/UtilityFunctions/AcyclicGraphTake.md
  Documentation/SymbolsAndFunctions/UtilityFunctions/CausalDensityDimension.md
  Kernel/AcyclicGraphTake.m
  Kernel/CausalDensityDimension.m
  README.md
  Tests/CausalDensityDimension.wlt
Labels: analysis, feature, wolfram language

#613 Separate file for libSetReplace loading
  Kernel/A00$buildData.m
  Kernel/A01$libSetReplace.m
  Kernel/setSubstitutionSystem$cpp.m
  Kernel/setSubstitutionSystem.m
Labels: refactor, wolfram language

#615 Fix broken links in Feature* functions
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md
Labels: weed
