Repository maxitg/SetReplace, pull requests merged in 2021-01, with the labels that each got.

#584 Fix spacing errors
  DevUtils/PackSetReplace.m
  DevUtils/init.m
  Kernel/buildData.m
  Kernel/setSubstitutionSystem$wl.m
  Tests/GeneralizedGridGraph.wlt
  Tests/HypergraphAutomorphismGroup.wlt
  Tests/HypergraphUnifications.wlt
  Tests/HypergraphUnificationsPlot.wlt
  Tests/RulePlot.wlt
  Tests/SetReplaceAll.wlt
  Tests/SetReplaceFixedPoint.wlt
  Tests/SetReplaceFixedPointList.wlt
  Tests/SetReplaceList.wlt
  Tests/WolframModel.wlt
  Tests/WolframModelEvolutionObject.wlt
  Tests/performance.wlt
  build.wls
  install.wls
  test.wls
Labels: weed, wolfram language

#583 Linter: whitespace formatter
  lint.sh
  scripts/checkLineWidth.sh
  scripts/whitespaceFormat.sh
Labels: bash, feature, infrastructure

#587 Anonymous Namespaces
  libSetReplace/Match.cpp
  libSetReplace/SetReplace.cpp
Labels: c++, optimization

#588 Managed Expressions
  Kernel/setSubstitutionSystem$cpp.m
  libSetReplace/SetReplace.cpp
  libSetReplace/SetReplace.hpp
Labels: c++, refactor, wolfram language

#589 Constant LibraryLink Arguments
  Kernel/setSubstitutionSystem$cpp.m
Labels: optimization, wolfram language

#590 Add WL Semicolons
  .github/CONTRIBUTING.md
  DevUtils/BuildLibSetReplace.m
  DevUtils/Console.m
  DevUtils/FileTreeHashes.m
  DevUtils/GitLink.m
  DevUtils/PackSetReplace.m
  DevUtils/Rasterization.m
  Kernel/GeneralizedGridGraph.m
  Kernel/HypergraphAutomorphismGroup.m
  Kernel/HypergraphPlot.m
  Kernel/HypergraphToGraph.m
  Kernel/HypergraphUnifications.m
  Kernel/HypergraphUnificationsPlot.m
  Kernel/IndexHypergraph.m
  Kernel/IsomorphicHypergraphQ.m
  Kernel/RandomHypergraph.m
  Kernel/RulePlot.m
  Kernel/SetReplace.m
  Kernel/SetReplaceAll.m
  Kernel/SetReplaceFixedPoint.m
  Kernel/SetReplaceFixedPointList.m
  Kernel/SetReplaceList.m
  Kernel/Subhypergraph.m
  Kernel/ToPatternRules.m
  Kernel/WolframModel.m
  Kernel/WolframModelEvolutionObject.m
  Kernel/WolframModelRuleValue.m
  Kernel/WolframPhysicsProjectStyleData.m
  Kernel/argumentsChecking.m
  Kernel/arrow.m
  Kernel/buildData.m
  Kernel/convexHullPolygon.m
  Kernel/globals.m
  Kernel/init.m
  Kernel/makeMessage.m
  Kernel/setSubstitutionSystem$cpp.m
  Kernel/setSubstitutionSystem$wl.m
  Kernel/setSubstitutionSystem.m
  Kernel/style.m
  Kernel/testUtilities.m
  Kernel/toCanonicalRules.m
  Kernel/utilities.m
Labels: refactor, wolfram language

#593 Changing section name "# Style" to "# Code Style".
  .github/CONTRIBUTING.md
Labels: weed

#591 Replacing makeMessage with General::msg
  Kernel/HypergraphToGraph.m
  Kernel/ToPatternRules.m
  Kernel/WolframModelEvolutionObject.m
  Kernel/makeMessage.m
  Kernel/setSubstitutionSystem$wl.m
  Kernel/setSubstitutionSystem.m
  Kernel/utilities.m
Labels: feature, wolfram language

#592 Adding "OptionNames" in SyntaxInformation to all exposed symbols
  .github/CONTRIBUTING.md
  Kernel/HypergraphUnificationsPlot.m
  Kernel/SetReplace.m
  Kernel/SetReplaceAll.m
  Kernel/SetReplaceFixedPoint.m
  Kernel/SetReplaceFixedPointList.m
  Kernel/SetReplaceList.m
  Kernel/WolframModel.m
  Tests/meta.wlt
Labels: convenience, wolfram language

#594 Renaming VertexCoordinateRules to VertexCoordinates.
  Documentation/SymbolsAndFunctions/HypergraphPlot.md
  Documentation/SymbolsAndFunctions/RulePlotOfWolframModel.md
  Kernel/HypergraphPlot.m
  Kernel/RulePlot.m
  Tests/HypergraphPlot.wlt
  Tests/RulePlot.wlt
Labels: breaking, refactor, wolfram language

#595 Allows using HEAD in performanceTest.wls and fixes it on CI
  .circleci/config.yml
  performanceTest.wls
Labels: infrastructure, weed, wolfram language

#601 Acyclic graph take
  Documentation/Images/AcyclicGraphTakeInput.png
  Documentation/Images/AcyclicGraphTakeOutput.png
  Documentation/SymbolsAndFunctions/UtilityFunctions/AcyclicGraphTake.md
  Kernel/AcyclicGraphTake.m
  README.md
  Tests/AcyclicGraphTake.wlt
Labels: feature, wolfram language

#596 Separate parts of `If`, `Catch`, `Check`, `Quiet` statements
  .github/CONTRIBUTING.md
  DevUtils/BuildLibSetReplace.m
  DevUtils/FileTreeHashes.m
  DevUtils/PackSetReplace.m
  DevUtils/Rasterization.m
  Kernel/GeneralizedGridGraph.m
  Kernel/HypergraphPlot.m
  Kernel/HypergraphUnificationsPlot.m
  Kernel/RandomHypergraph.m
  Kernel/RulePlot.m
  Kernel/SetReplace.m
  Kernel/SetReplaceAll.m
  Kernel/SetReplaceFixedPoint.m
  Kernel/SetReplaceFixedPointList.m
  Kernel/SetReplaceList.m
  Kernel/ToPatternRules.m
  Kernel/WolframModel.m
  Kernel/WolframModelEvolutionObject.m
  Kernel/arrow.m
  Kernel/setSubstitutionSystem$cpp.m
  Kernel/setSubstitutionSystem$wl.m
  Kernel/setSubstitutionSystem.m
  Tests/WolframModel.wlt
  Tests/evolutionConsistency.wlt
  Tests/meta.wlt
  performanceTest.wls
  test.wls
Labels: refactor, wolfram language
