Repository maxitg/SetReplace, pull requests merged in 2021-03, with the labels that each got.

#599 Basic Type System
  Documentation/TypeSystem.md
  Kernel/A1$typeSystem.m
  Kernel/init.m
  Tests/typeSystem.wlt
Labels: analysis, feature, wolfram language

#616 Obtain googletest from master
  CMakeLists.txt
Labels: cmake, weed

#617 Multihistory
  Documentation/SymbolsAndFunctions/TypeSystem/Multihistory.md
  Documentation/SymbolsAndFunctions/TypeSystem/README.md
  Documentation/SymbolsAndFunctions/TypeSystem/SetReplaceTypeConvert.md
  Documentation/TypeSystem.md
  Kernel/Multihistory.m
  Tests/Multihistory.wlt
Labels: feature, wolfram language

#618 Basic Type System Utilities
  Documentation/Images/SetReplaceObjectQOfMultihistory.png
  Documentation/Images/SetReplaceObjectTypeOfMultihistory.png
  Documentation/SymbolsAndFunctions/TypeSystem/$SetReplaceProperties.md
  Documentation/SymbolsAndFunctions/TypeSystem/$SetReplaceTypes.md
  Documentation/SymbolsAndFunctions/TypeSystem/README.md
  Documentation/SymbolsAndFunctions/TypeSystem/SetReplaceObjectQ.md
  Documentation/SymbolsAndFunctions/TypeSystem/SetReplaceObjectType.md
  Documentation/SymbolsAndFunctions/TypeSystem/SetReplaceTypeConvert.md
  Kernel/A1$typeSystem.m
  Tests/typeSystem.wlt
Labels: feature, wolfram language

#620 Template for the Student Project Proposal
  .github/ISSUE_TEMPLATE/student_project.md
Labels: english

#619 Adding "MaxDestroyerEvents" as a step spec to WolframModel (C++)
  Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md
  Kernel/setSubstitutionSystem$cpp.m
  Kernel/setSubstitutionSystem.m
  Tests/WolframModel.wlt
  libSetReplace/Event.cpp
  libSetReplace/Event.hpp
  libSetReplace/Set.cpp
  libSetReplace/Set.hpp
  libSetReplace/SetReplace.cpp
  libSetReplace/test/Set_test.cpp
  libSetReplace/test/profile_tests.cpp
Labels: c++, evolution, feature

#621 $SetReplaceTypeGraph
  Documentation/Images/$SetReplaceTypeGraph.png
  Documentation/SymbolsAndFunctions/TypeSystem/$SetReplaceTypeGraph.md
  Documentation/SymbolsAndFunctions/TypeSystem/README.md
  Documentation/SymbolsAndFunctions/TypeSystem/SetReplaceMethodImplementation.md
  Documentation/SymbolsAndFunctions/TypeSystem/SetReplaceProperty.md
  Documentation/SymbolsAndFunctions/TypeSystem/SetReplaceType.md
  Kernel/A0$style.m
  Kernel/A1$typeSystem.m
  Tests/typeSystem.wlt
Labels: feature, wolfram language

#625 Fix labels for list-types in $SetReplaceTypeGraph
  Kernel/A1$typeSystem.m
Labels: weed

#627 Update minimum Wolfram Language version to 12.2.0
  .circleci/config.yml
  PacletInfo.m
  README.md
Labels: infrastructure

#626 GenerateMultihistory
  Kernel/A1$GenerateMultihistory.m
  Kernel/init.m
  Tests/GenerateMultihistory.wlt
Labels: feature, wolfram language

#628 Test Wolfram Language 12.3
  .circleci/config.yml
  .circleci/test.sh
Labels: bash, infrastructure, test

#629 Allow trailing comments in test files
  test.wls
Labels: infrastructure, weed, wolfram language

#624 MultisetSubstitutionSystem
  .circleci/test.sh
  Kernel/A0$messages.m
  Kernel/MultisetSubstitutionSystem.m
  Kernel/MultisetToWolframModelEvolutionObject.m
  Tests/MultisetSubstitutionSystem.wlt
  Tests/hypergraphMatching.wlt
  Tests/matching.wlt
  Tests/typeSystem.wlt
Labels: evolution, feature, wolfram language

#631 Rasterization: allow filenames starting with $
  DevUtils/Rasterization.m
Labels: convenience, infrastructure, wolfram language
